<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE card [
  <!ELEMENT card (scan+)>
  <!ATTLIST card name CDATA #REQUIRED>
  <!ELEMENT scan (param+)>
  <!ATTLIST scan name CDATA #REQUIRED>
  <!ELEMENT param (value+)>
  <!ATTLIST param
    name CDATA #REQUIRED
    display (on|off) "off"
    type (float|integer|string|enum|unknown) "unknown"
  >
  <!ELEMENT value (#PCDATA)>
]>
<card name="SR_ADULT_007">
  <scan name="Quiet_Survey">
    <param name="EX_geometry_seperator" display="off" type="integer">
      <value>1634755923</value>
    </param>
    <param name="EX_ACQ_nucleus" display="off" type="enum">
      <value>H</value>
    </param>
    <param name="EX_GEO_stacks_coil_ids" display="off" type="enum">
      <value>SENSE_HEAD_32P</value>
      <value>SENSE_HEAD_32P</value>
      <value>SENSE_HEAD_32P</value>
      <value>SENSE_HEAD_8</value>
      <value>SENSE_HEAD_8</value>
      <value>SENSE_HEAD_8</value>
      <value>SENSE_HEAD_8</value>
      <value>SENSE_HEAD_8</value>
      <value>SENSE_HEAD_8</value>
      <value>SENSE_HEAD_8</value>
      <value>SENSE_HEAD_8</value>
      <value>SENSE_HEAD_8</value>
      <value>SENSE_HEAD_8</value>
      <value>SENSE_HEAD_8</value>
      <value>SENSE_HEAD_8</value>
      <value>SENSE_HEAD_8</value>
      <value>SENSE_HEAD_8</value>
      <value>SENSE_HEAD_8</value>
      <value>SENSE_HEAD_8</value>
      <value>SENSE_HEAD_8</value>
    </param>
    <param name="EX_GEO_stacks_cbb1_coils" display="off" type="enum">
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
    </param>
    <param name="EX_GEO_stacks_cbb2_coils" display="off" type="enum">
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
      <value>O_COIL</value>
    </param>
    <param name="EX_GEO_stacks_coil_parts" display="off" type="enum">
      <value>R_AB</value>
      <value>R_AB</value>
      <value>R_AB</value>
      <value>SENSE</value>
      <value>SENSE</value>
      <value>SENSE</value>
      <value>SENSE</value>
      <value>SENSE</value>
      <value>SENSE</value>
      <value>SENSE</value>
      <value>SENSE</value>
      <value>SENSE</value>
      <value>SENSE</value>
      <value>SENSE</value>
      <value>SENSE</value>
      <value>SENSE</value>
      <value>SENSE</value>
      <value>SENSE</value>
      <value>SENSE</value>
      <value>SENSE</value>
    </param>
    <param name="EX_GEO_stacks_channel_combis" display="off" type="integer">
      <value>65535</value>
      <value>65535</value>
      <value>65535</value>
      <value>255</value>
      <value>255</value>
      <value>255</value>
      <value>255</value>
      <value>255</value>
      <value>255</value>
      <value>255</value>
      <value>255</value>
      <value>255</value>
      <value>255</value>
      <value>255</value>
      <value>255</value>
      <value>255</value>
      <value>255</value>
      <value>255</value>
      <value>255</value>
      <value>255</value>
    </param>
    <param name="EX_GEO_stacks_coil_connections" display="off" type="enum">
      <value>DEFAULT</value>
      <value>DEFAULT</value>
      <value>DEFAULT</value>
      <value>DEFAULT</value>
      <value>DEFAULT</value>
      <value>DEFAULT</value>
      <value>DEFAULT</value>
      <value>DEFAULT</value>
      <value>DEFAULT</value>
      <value>DEFAULT</value>
      <value>DEFAULT</value>
      <value>DEFAULT</value>
      <value>DEFAULT</value>
      <value>DEFAULT</value>
      <value>DEFAULT</value>
      <value>DEFAULT</value>
      <value>DEFAULT</value>
      <value>DEFAULT</value>
      <value>DEFAULT</value>
      <value>DEFAULT</value>
    </param>
    <param name="EX_GEO_stacks_coil_2_ids" display="off" type="enum">
      <value>SENSE_HEAD_32AH</value>
      <value>SENSE_HEAD_32AH</value>
      <value>SENSE_HEAD_32AH</value>
      <value>HEAD_QUAD</value>
      <value>HEAD_QUAD</value>
      <value>HEAD_QUAD</value>
      <value>HEAD_QUAD</value>
      <value>HEAD_QUAD</value>
      <value>HEAD_QUAD</value>
      <value>HEAD_QUAD</value>
      <value>HEAD_QUAD</value>
      <value>HEAD_QUAD</value>
      <value>HEAD_QUAD</value>
      <value>HEAD_QUAD</value>
      <value>HEAD_QUAD</value>
      <value>HEAD_QUAD</value>
      <value>HEAD_QUAD</value>
      <value>HEAD_QUAD</value>
      <value>HEAD_QUAD</value>
      <value>HEAD_QUAD</value>
    </param>
    <param name="EX_GEO_stacks_coil_2_parts" display="off" type="enum">
      <value>R_AB</value>
      <value>R_AB</value>
      <value>R_AB</value>
      <value>_A</value>
      <value>_A</value>
      <value>_A</value>
      <value>_A</value>
      <value>_A</value>
      <value>_A</value>
      <value>_A</value>
      <value>_A</value>
      <value>_A</value>
      <value>_A</value>
      <value>_A</value>
      <value>_A</value>
      <value>_A</value>
      <value>_A</value>
      <value>_A</value>
      <value>_A</value>
      <value>_A</value>
    </param>
    <param name="EX_GEO_stacks_channel_combis_2" display="off" type="integer">
      <value>65535</value>
      <value>65535</value>
      <value>65535</value>
      <value>0</value>
      <value>0</value>
      <value>0</value>
      <value>0</value>
      <value>0</value>
      <value>0</value>
      <value>0</value>
      <value>0</value>
      <value>0</value>
      <value>0</value>
      <value>0</value>
      <value>0</value>
      <value>0</value>
      <value>0</value>
      <value>0</value>
      <value>0</value>
      <value>0</value>
    </param>
    <param name="EX_GEO_dual_connector" display="off" type="enum">
      <value>YES</value>
    </param>
    <param name="EX_GEO_multi_coil" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_PROC_hom_filter" display="off" type="enum">
      <value>O</value>
    </param>
    <param name="EX_PROC_clear_enable" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_GEO_fov" display="on" type="float">
      <value>250.000000</value>
    </param>
    <param name="EX_GEO_fov_p" display="on" type="float">
      <value>250.000000</value>
    </param>
    <param name="EX_GEO_stacks_fov_ss" display="off" type="float">
      <value>50.000000</value>
      <value>50.000000</value>
      <value>50.000000</value>
      <value>50.000000</value>
      <value>50.000000</value>
      <value>50.000000</value>
      <value>50.000000</value>
      <value>50.000000</value>
      <value>50.000000</value>
      <value>50.000000</value>
      <value>50.000000</value>
      <value>50.000000</value>
      <value>50.000000</value>
      <value>50.000000</value>
      <value>50.000000</value>
      <value>50.000000</value>
      <value>50.000000</value>
      <value>50.000000</value>
      <value>50.000000</value>
      <value>50.000000</value>
    </param>
    <param name="EX_GEO_voxel_size_m" display="on" type="float">
      <value>0.976563</value>
    </param>
    <param name="EX_GEO_voxel_size_p" display="on" type="float">
      <value>1.953125</value>
    </param>
    <param name="EX_GEO_voxel_size_s" display="on" type="float">
      <value>10.000000</value>
    </param>
    <param name="EX_PROC_recon_voxel_size" display="off" type="float">
      <value>0.976562</value>
    </param>
    <param name="EX_GEO_rect_fov_perc" display="off" type="float">
      <value>100.000000</value>
    </param>
    <param name="EX_ACQ_foldover_sup" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_ACQ_scan_resol" display="off" type="integer">
      <value>256</value>
    </param>
    <param name="EX_PROC_recon_resol" display="off" type="integer">
      <value>256</value>
    </param>
    <param name="EX_ACQ_reduced_acq_time" display="off" type="float">
      <value>50.000000</value>
    </param>
    <param name="EX_GEO_sense_enable" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_ACQ_kt_enable" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_GEO_stacks" display="on" type="integer">
      <value>3</value>
    </param>
    <param name="EX_GEO_stacks_types" display="off" type="enum">
      <value>PARALLEL_STACK</value>
      <value>PARALLEL_STACK</value>
      <value>PARALLEL_STACK</value>
      <value>PARALLEL_STACK</value>
      <value>PARALLEL_STACK</value>
      <value>PARALLEL_STACK</value>
      <value>PARALLEL_STACK</value>
      <value>PARALLEL_STACK</value>
      <value>PARALLEL_STACK</value>
      <value>PARALLEL_STACK</value>
      <value>PARALLEL_STACK</value>
      <value>PARALLEL_STACK</value>
      <value>PARALLEL_STACK</value>
      <value>PARALLEL_STACK</value>
      <value>PARALLEL_STACK</value>
      <value>PARALLEL_STACK</value>
      <value>PARALLEL_STACK</value>
      <value>PARALLEL_STACK</value>
      <value>PARALLEL_STACK</value>
      <value>PARALLEL_STACK</value>
    </param>
    <param name="EX_GEO_stacks_slices" display="off" type="integer">
      <value>3</value>
      <value>3</value>
      <value>3</value>
      <value>3</value>
      <value>3</value>
      <value>3</value>
      <value>3</value>
      <value>3</value>
      <value>3</value>
      <value>3</value>
      <value>3</value>
      <value>3</value>
      <value>3</value>
      <value>3</value>
      <value>3</value>
      <value>3</value>
      <value>3</value>
      <value>3</value>
      <value>3</value>
      <value>3</value>
    </param>
    <param name="EX_GEO_slice_thickness" display="off" type="float">
      <value>10.000000</value>
    </param>
    <param name="EX_GEO_slice_gap_mode" display="off" type="enum">
      <value>USER_DEF</value>
    </param>
    <param name="EX_GEO_stacks_slice_gaps" display="off" type="float">
      <value>10.000000</value>
      <value>10.000000</value>
      <value>10.000000</value>
      <value>10.000000</value>
      <value>10.000000</value>
      <value>10.000000</value>
      <value>10.000000</value>
      <value>10.000000</value>
      <value>10.000000</value>
      <value>10.000000</value>
      <value>10.000000</value>
      <value>10.000000</value>
      <value>10.000000</value>
      <value>10.000000</value>
      <value>10.000000</value>
      <value>10.000000</value>
      <value>10.000000</value>
      <value>10.000000</value>
      <value>10.000000</value>
      <value>10.000000</value>
    </param>
    <param name="EX_GEO_stacks_orientations" display="off" type="enum">
      <value>SAGITTAL</value>
      <value>CORONAL</value>
      <value>RANSVERSAL</value>
      <value>RANSVERSAL</value>
      <value>RANSVERSAL</value>
      <value>RANSVERSAL</value>
      <value>RANSVERSAL</value>
      <value>RANSVERSAL</value>
      <value>RANSVERSAL</value>
      <value>RANSVERSAL</value>
      <value>RANSVERSAL</value>
      <value>RANSVERSAL</value>
      <value>RANSVERSAL</value>
      <value>RANSVERSAL</value>
      <value>RANSVERSAL</value>
      <value>RANSVERSAL</value>
      <value>RANSVERSAL</value>
      <value>RANSVERSAL</value>
      <value>RANSVERSAL</value>
      <value>RANSVERSAL</value>
    </param>
    <param name="EX_GEO_stacks_prep_dirs" display="off" type="enum">
      <value>A</value>
      <value>LR</value>
      <value>LR</value>
      <value>LR</value>
      <value>LR</value>
      <value>LR</value>
      <value>LR</value>
      <value>LR</value>
      <value>LR</value>
      <value>LR</value>
      <value>LR</value>
      <value>LR</value>
      <value>LR</value>
      <value>LR</value>
      <value>LR</value>
      <value>LR</value>
      <value>LR</value>
      <value>LR</value>
      <value>LR</value>
      <value>LR</value>
    </param>
    <param name="EX_GEO_stacks_fat_shift_dirs" display="off" type="enum">
      <value>H</value>
      <value>H</value>
      <value>F</value>
      <value>F</value>
      <value>F</value>
      <value>F</value>
      <value>F</value>
      <value>F</value>
      <value>F</value>
      <value>F</value>
      <value>F</value>
      <value>F</value>
      <value>F</value>
      <value>F</value>
      <value>F</value>
      <value>F</value>
      <value>F</value>
      <value>F</value>
      <value>F</value>
      <value>F</value>
    </param>
    <param name="EX_GEO_stacks_ap_offcentres" display="off" type="float">
      <value>-20.000000</value>
      <value>0.000000</value>
      <value>-20.000000</value>
      <value>-20.000000</value>
      <value>-20.000000</value>
      <value>-20.000000</value>
      <value>-20.000000</value>
      <value>-20.000000</value>
      <value>-20.000000</value>
      <value>-20.000000</value>
      <value>-20.000000</value>
      <value>-20.000000</value>
      <value>-20.000000</value>
      <value>-20.000000</value>
      <value>-20.000000</value>
      <value>-20.000000</value>
      <value>-20.000000</value>
      <value>-20.000000</value>
      <value>-20.000000</value>
      <value>-20.000000</value>
    </param>
    <param name="EX_GEO_stacks_lr_offcentres" display="off" type="float">
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
    </param>
    <param name="EX_GEO_stacks_fh_offcentres" display="off" type="float">
      <value>0.000000</value>
      <value>20.000000</value>
      <value>20.000000</value>
      <value>20.000000</value>
      <value>20.000000</value>
      <value>20.000000</value>
      <value>20.000000</value>
      <value>20.000000</value>
      <value>20.000000</value>
      <value>20.000000</value>
      <value>20.000000</value>
      <value>20.000000</value>
      <value>20.000000</value>
      <value>20.000000</value>
      <value>20.000000</value>
      <value>20.000000</value>
      <value>20.000000</value>
      <value>20.000000</value>
      <value>20.000000</value>
      <value>20.000000</value>
    </param>
    <param name="EX_GEO_stacks_ap_angulations" display="off" type="float">
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
    </param>
    <param name="EX_GEO_stacks_lr_angulations" display="off" type="float">
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
    </param>
    <param name="EX_GEO_stacks_fh_angulations" display="off" type="float">
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
    </param>
    <param name="EX_ACQ_slice_order" display="off" type="enum">
      <value>DFAULT</value>
    </param>
    <param name="EX_ACQ_stack_order" display="off" type="enum">
      <value>ASCEND</value>
    </param>
    <param name="EX_GEO_move_table_per_stack" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_GEO_large_table_movement" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_GEO_stack_alignment" display="off" type="enum">
      <value>ONE</value>
    </param>
    <param name="EX_GEO_stack_display_order" display="off" type="enum">
      <value>ONE</value>
    </param>
    <param name="EX_GEO_plan_align" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_REST_slabs" display="off" type="integer">
      <value>0</value>
    </param>
    <param name="EX_TRACK_tracking" display="off" type="enum">
      <value>NNE</value>
    </param>
    <param name="EX_GEO_ia_positioning" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_GEO_external_control" display="off" type="enum">
      <value>O</value>
    </param>
    <param name="EX_USEGEOM_geometry_names" display="off" type="string">
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
    </param>
    <param name="EX_USEGEOM_stack_use_geoms" display="off" type="enum">
      <value>NONE</value>
      <value>NONE</value>
      <value>NONE</value>
      <value>NONE</value>
      <value>NONE</value>
      <value>NONE</value>
      <value>NONE</value>
      <value>NONE</value>
      <value>NONE</value>
      <value>NONE</value>
      <value>NONE</value>
      <value>NONE</value>
      <value>NONE</value>
      <value>NONE</value>
      <value>NONE</value>
      <value>NONE</value>
      <value>NONE</value>
      <value>NONE</value>
      <value>NONE</value>
      <value>NONE</value>
    </param>
    <param name="EX_USEGEOM_stack_use_geom_names" display="off" type="string">
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
      <value></value>
    </param>
    <param name="EX_GEO_allow_table_movement" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_GEO_patient_position" display="off" type="enum">
      <value>HAD_FIRST</value>
    </param>
    <param name="EX_GEO_patient_orientation" display="off" type="enum">
      <value>UPINE</value>
    </param>
    <param name="EX_contrast_seperator" display="off" type="integer">
      <value>1634755923</value>
    </param>
    <param name="EX_ACQ_scan_type" display="off" type="enum">
      <value>MAGING</value>
    </param>
    <param name="EX_ACQ_scan_mode" display="off" type="enum">
      <value>M2D</value>
    </param>
    <param name="EX_ACQ_imaging_sequence" display="off" type="enum">
      <value>FFE</value>
    </param>
    <param name="EX_FFE_ceffe" display="off" type="enum">
      <value>T1</value>
    </param>
    <param name="EX_ACQ_mode" display="off" type="enum">
      <value>CARTESIAN</value>
    </param>
    <param name="EX_ACQ_fast_imaging_mode" display="off" type="enum">
      <value>TFE</value>
    </param>
    <param name="EX_ACQ_shot_mode" display="off" type="enum">
      <value>MH</value>
    </param>
    <param name="EX_TFE_factor" display="off" type="integer">
      <value>64</value>
    </param>
    <param name="EX_TFE_startup_profs_enum" display="off" type="enum">
      <value>DEFAULT</value>
    </param>
    <param name="EX_TFE_interval_enum" display="off" type="enum">
      <value>SHORTEST</value>
    </param>
    <param name="EX_ACQ_profile_order_sel" display="off" type="enum">
      <value>LINEAR</value>
    </param>
    <param name="EX_ACQ_echoes" display="off" type="integer">
      <value>1</value>
    </param>
    <param name="EX_ACQ_partial_echo" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_FFE_shifted_echo" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_ACQ_first_echo_time_enum" display="on" type="enum">
      <value>INPHASE</value>
    </param>
    <param name="EX_ACQ_first_echo_time" display="on" type="float">
      <value>6.906288</value>
    </param>
    <param name="EX_ACQ_flip_angle" display="off" type="float">
      <value>15.000000</value>
    </param>
    <param name="EX_ACQ_ffe_rep_time_enum" display="on" type="enum">
      <value>SHORTEST</value>
    </param>
    <param name="EX_ACQ_partial_matrix" display="off" type="enum">
      <value>O</value>
    </param>
    <param name="EX_ACQ_water_fat_shift" display="off" type="enum">
      <value>USER_DEF</value>
    </param>
    <param name="EX_ACQ_user_def_water_fat_shift" display="off" type="float">
      <value>3.500000</value>
    </param>
    <param name="EX_ACQ_RF_shim_data" display="off" type="float">
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
      <value>0.000000</value>
    </param>
    <param name="EX_AS_shim" display="off" type="enum">
      <value>EFAULT</value>
    </param>
    <param name="EX_shim_from_idl" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_calculate_shim_now" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_shim_freq_det" display="off" type="enum">
      <value>AUTO</value>
    </param>
    <param name="EX_shim_second_x1" display="off" type="float">
      <value>0.000000</value>
    </param>
    <param name="EX_shim_second_y1" display="off" type="float">
      <value>0.000000</value>
    </param>
    <param name="EX_shim_second_z1" display="off" type="float">
      <value>0.000000</value>
    </param>
    <param name="EX_shim_second_z2" display="off" type="float">
      <value>0.000000</value>
    </param>
    <param name="EX_shim_second_zx" display="off" type="float">
      <value>0.000000</value>
    </param>
    <param name="EX_shim_second_zy" display="off" type="float">
      <value>0.000000</value>
    </param>
    <param name="EX_shim_second_x2y2" display="off" type="float">
      <value>0.000000</value>
    </param>
    <param name="EX_shim_second_2xy" display="off" type="float">
      <value>0.000000</value>
    </param>
    <param name="EX_shim_second_z3" display="off" type="float">
      <value>0.000000</value>
    </param>
    <param name="EX_shim_second_z2x" display="off" type="float">
      <value>0.000000</value>
    </param>
    <param name="EX_shim_second_z2y" display="off" type="float">
      <value>0.000000</value>
    </param>
    <param name="EX_shim_second_zx2y2" display="off" type="float">
      <value>0.000000</value>
    </param>
    <param name="EX_shim_second_xyz" display="off" type="float">
      <value>0.000000</value>
    </param>
    <param name="EX_shim_second_x3" display="off" type="float">
      <value>0.000000</value>
    </param>
    <param name="EX_shim_second_y3" display="off" type="float">
      <value>0.000000</value>
    </param>
    <param name="EX_shim_offset_freq" display="off" type="integer">
      <value>0</value>
    </param>
    <param name="EX_shim_nav_offset_freq" display="off" type="integer">
      <value>0</value>
    </param>
    <param name="EX_shim_nav_x1" display="off" type="float">
      <value>0.000000</value>
    </param>
    <param name="EX_shim_nav_y1" display="off" type="float">
      <value>0.000000</value>
    </param>
    <param name="EX_shim_nav_z1" display="off" type="float">
      <value>0.000000</value>
    </param>
    <param name="EX_ACQ_dixon" display="off" type="enum">
      <value>O</value>
    </param>
    <param name="EX_ACQ_dixon_startup_cycles_enum" display="off" type="enum">
      <value>DEFAULT</value>
    </param>
    <param name="EX_SPIR_fat_suppression" display="off" type="enum">
      <value>O</value>
    </param>
    <param name="EX_SPIR_water_suppression" display="off" type="enum">
      <value>O</value>
    </param>
    <param name="EX_TFEPP_prepulses" display="off" type="enum">
      <value>INV</value>
    </param>
    <param name="EX_TFEPP_pre_slice_select" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_TFEPP_pre_shared_prepulse" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_TFEPP_pre_T1_delay_enum" display="off" type="enum">
      <value>USER_DEF</value>
    </param>
    <param name="EX_TFEPP_pre_T1_delay" display="off" type="float">
      <value>800.000000</value>
    </param>
    <param name="EX_TFEPP_pre_T1_mixed_sequence" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_MTC_enable" display="off" type="enum">
      <value>O</value>
    </param>
    <param name="EX_T2PREP_enable" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_REPP_enable" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_DIFF_enable" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_ELASTO_enable" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_COIL_control_SAR_mode" display="off" type="enum">
      <value>HIGH</value>
    </param>
    <param name="EX_COIL_control_B1_mode" display="off" type="enum">
      <value>DEFAULT</value>
    </param>
    <param name="EX_MULTIX_SAR_mode" display="off" type="enum">
      <value>ATO</value>
    </param>
    <param name="EX_ACQ_pns_mode" display="off" type="enum">
      <value>LOW</value>
    </param>
    <param name="EX_ACQ_gradient_mode" display="off" type="enum">
      <value>RGULAR</value>
    </param>
    <param name="EX_ACQ_silent_mode" display="off" type="enum">
      <value>NO</value>
    </param>
    <param name="EX_motion_seperator" display="off" type="integer">
      <value>0</value>
    </param>
    <param name="EX_CARD_sync" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_CARD_high_heart_rate" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_RESP_synch" display="off" type="enum">
      <value>O</value>
    </param>
    <param name="EX_RNAV_resp_comp" display="off" type="enum">
      <value>OF</value>
    </param>
    <param name="EX_RNAV_weighted_gating" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_ACQ_flow_compensation" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_FFE_phase_nav" display="off" type="enum">
      <value>N</value>
    </param>
    <param name="EX_TFE_randomise_shots" display="off" type="enum">
      <value>N</value>